name: Build and deploy Python app to Azure Web App - mydjangoapp123

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: CI sanity (install deps)
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: backend/   # <- package root contains manage.py and requirements.txt

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./backend

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2CF9D55ABC214E43B6E83619F91DC8DD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C0438554C61F43C88EE56E2B75697C90 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_667C208615244A88A6C0017C0A7CB696 }}

      # Ensure Oryx build happens in App Service and Django static files are collected
      - name: Set app settings (once per app)
        run: |
          az webapp config appsettings set -g rg-rub-project -n mydjangoapp123 --settings \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            ORYX_PYTHON_VERSION=3.11 \
            DJANGO_SETTINGS_MODULE=Dashboard.settings \
            PYTHONPATH=/home/site/wwwroot \
            WEBSITES_PORT=8000

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: mydjangoapp123
          slot-name: Production
          package: ./backend
          # Start gunicorn after Oryx build
          startup-command: >
            gunicorn Dashboard.wsgi:application
            --bind=0.0.0.0:8000
            --timeout 600

      - name: Restart App
        run: az webapp restart --name mydjangoapp123 --resource-group rg-rub-project


